name = "delhi-metro"
main = "src/worker.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 */4 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "delhi-metro-db"
database_id = "b3983015-0a87-4a9a-9101-daf94e434b09"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "CACHE"
id = "01c2365f1a974574bcb34d964080a376"

[[durable_objects.bindings]]
name = "GRAPH"
class_name = "GraphDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GraphDO"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true
